./scripts/removeBadImages.sh: some warnings

diff --git a/.github/workflows/ci_compile.yml b/.github/workflows/ci_compile.yml
--- a/.github/workflows/ci_compile.yml
+++ b/.github/workflows/ci_compile.yml
@@ -180,6 +180,16 @@ jobs:
                 #SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
                 shellcheck $i -e SC2086 -e SC2219 -e SC2181
                 ;;
+              ./scripts/removeBadImages.sh)
+                #SC1090: Can't follow non-constant source. Use a directive to specify location.
+                #SC2086: Double quote to prevent globbing and word splitting.
+                #SC2166: Prefer [ p ] || [ q ] as [ p -o q ] is not well defined.
+                #SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
+                #SC2188: This redirection doesn't have a command. Move to its command (or use 'true' as no-op).
+                #SC2196: egrep is non-standard and deprecated. Use grep -E instead.
+                #SC2219: Instead of 'let expr', prefer (( expr )) .
+                shellcheck $i -e SC1090 -e SC2086 -e SC2166 -e SC2164 -e SC2188 -e SC2196 -e SC2219
+                ;;
               *)
                 shellcheck $i
                 ;;
@@ -190,6 +200,6 @@ jobs:
           done
           if [ $err -ne 0 ]; then
             echo '::echo::on'
-            echo "::warning:: bash or shellcheck found problems in scripts. Please fix it or add some excludes (-e SC....) here in this file."
+            echo "::error:: bash or shellcheck found problems in scripts. Please fix it or add some excludes (-e SC....) here in this file."
           fi
           exit $err
